# SPDX-FileCopyrightText: Copyright (c) 2025-2026 Max Trunnikov
# SPDX-License-Identifier: MIT
---
docker:
  image: yegor256/rultor-image:1.23.1
assets:
  npmrc: maxonfjvipon/secrets#.npmrc
install: |
  pip install git+https://chromium.googlesource.com/external/gyp
  npm install --no-color
  sudo npm install --no-color --global grunt-cli
  npm uninstall --no-color grunt-cli
  npm install --no-color mocha
  pdd -f /dev/null -v
release:
  pre: false
  script: |
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    sed -i "s/0\.0\.0/${tag}/" package.json
    sed -i "s/0\.0\.0/${tag}/" src/version.js
    sed -i "s/0000-00-00/$(date +%Y-%m-%d)/" src/version.js
    npm test
    git commit -am "set version to ${tag}"
    chmod 600 ../npmrc
    echo "xslint dry run:"
    npm publish --dry-run --userconfig=../npmrc || exit 1
    echo "Check if xslint exists:"
    npm view xlint@${tag} && exit 1
    echo "Publishing xslint:"
    npm publish --userconfig=../npmrc --access=public
merge:
  script: |-
    npm test
